FROM openjdk:11-jdk-slim
WORKDIR /usr/local/app
ARG REVISION
COPY ./com.godeltech.bikesharing-backend/build/libs/com.godeltech.bikesharing-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-jar","app.jar"]